# Display
USE_DEVICE_SPECIFIC_DISPLAY := true
DEVICE_SPECIFIC_DISPLAY_PATH := $(COMMON_DEVICE_PATH)/display
TARGET_DISPLAY_USE_RETIRE_FENCE := true

# Adreno driver
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true

# Ion
TARGET_USES_ION := true

# OpenGL
USE_OPENGL_RENDERER := true
